// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: question.proto

package server

import (
	"context"

	"backend/microservices/question/internal/logic"
	"backend/microservices/question/internal/svc"
	"backend/microservices/question/pb/question"
)

type QuestionServer struct {
	svcCtx *svc.ServiceContext
	question.UnimplementedQuestionServer
}

func NewQuestionServer(svcCtx *svc.ServiceContext) *QuestionServer {
	return &QuestionServer{
		svcCtx: svcCtx,
	}
}

func (s *QuestionServer) AddQuestion(ctx context.Context, in *question.AddQuestionReq) (*question.AddQuestionResp, error) {
	l := logic.NewAddQuestionLogic(ctx, s.svcCtx)
	return l.AddQuestion(in)
}

func (s *QuestionServer) DeleteQuestion(ctx context.Context, in *question.DeleteQuestionReq) (*question.DeleteQuestionResp, error) {
	l := logic.NewDeleteQuestionLogic(ctx, s.svcCtx)
	return l.DeleteQuestion(in)
}

func (s *QuestionServer) UpdateQuestion(ctx context.Context, in *question.UpdateQuestionReq) (*question.UpdateQuestionResp, error) {
	l := logic.NewUpdateQuestionLogic(ctx, s.svcCtx)
	return l.UpdateQuestion(in)
}

func (s *QuestionServer) GetQuestionInfo(ctx context.Context, in *question.GetQuestionInfoReq) (*question.GetQuestionInfoResp, error) {
	l := logic.NewGetQuestionInfoLogic(ctx, s.svcCtx)
	return l.GetQuestionInfo(in)
}

func (s *QuestionServer) GetQuestionList(ctx context.Context, in *question.GetQuestionListReq) (*question.GetQuestionListResp, error) {
	l := logic.NewGetQuestionListLogic(ctx, s.svcCtx)
	return l.GetQuestionList(in)
}

func (s *QuestionServer) GetQuestionJudgeCase(ctx context.Context, in *question.GetQuestionJudgeCaseReq) (*question.GetQuestionJudgeCaseResp, error) {
	l := logic.NewGetQuestionJudgeCaseLogic(ctx, s.svcCtx)
	return l.GetQuestionJudgeCase(in)
}

func (s *QuestionServer) GetQuestionJudgeConfig(ctx context.Context, in *question.GetQuestionJudgeConfigReq) (*question.GetQuestionJudgeConfigResp, error) {
	l := logic.NewGetQuestionJudgeConfigLogic(ctx, s.svcCtx)
	return l.GetQuestionJudgeConfig(in)
}
