// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: competition.proto

package competitionclient

import (
	"context"

	"backend/microservices/competition/pb/competition"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCompetitionReq                = competition.AddCompetitionReq
	AddCompetitionResp               = competition.AddCompetitionResp
	AttendCompetitionReq             = competition.AttendCompetitionReq
	AttendCompetitionResp            = competition.AttendCompetitionResp
	CompetitionAttendance            = competition.CompetitionAttendance
	CompetitionInfo                  = competition.CompetitionInfo
	CompetitionScore                 = competition.CompetitionScore
	ContestAccessCheckReq            = competition.ContestAccessCheckReq
	ContestAccessCheckResp           = competition.ContestAccessCheckResp
	DeleteCompetitionReq             = competition.DeleteCompetitionReq
	DeleteCompetitionResp            = competition.DeleteCompetitionResp
	ExecDetail                       = competition.ExecDetail
	GetCompetitionInfoReq            = competition.GetCompetitionInfoReq
	GetCompetitionInfoResp           = competition.GetCompetitionInfoResp
	GetCompetitionListReq            = competition.GetCompetitionListReq
	GetCompetitionListResp           = competition.GetCompetitionListResp
	GetCompetitionQuestionDetailReq  = competition.GetCompetitionQuestionDetailReq
	GetCompetitionQuestionDetailResp = competition.GetCompetitionQuestionDetailResp
	GetCompetitionQuestionListReq    = competition.GetCompetitionQuestionListReq
	GetCompetitionQuestionListResp   = competition.GetCompetitionQuestionListResp
	GetCompetitionRankListReq        = competition.GetCompetitionRankListReq
	GetCompetitionRankListResp       = competition.GetCompetitionRankListResp
	IsUserInCompetitionReq           = competition.IsUserInCompetitionReq
	IsUserInCompetitionResp          = competition.IsUserInCompetitionResp
	JudgeResult                      = competition.JudgeResult
	QuestionBasicInfo                = competition.QuestionBasicInfo
	QuestionDetailInfo               = competition.QuestionDetailInfo
	ScoreDetail                      = competition.ScoreDetail
	SubmitCompetitionQuestionReq     = competition.SubmitCompetitionQuestionReq
	SubmitCompetitionQuestionResp    = competition.SubmitCompetitionQuestionResp
	UpdateCompetitionReq             = competition.UpdateCompetitionReq
	UpdateCompetitionResp            = competition.UpdateCompetitionResp

	Competition interface {
		GetCompetitionList(ctx context.Context, in *GetCompetitionListReq, opts ...grpc.CallOption) (*GetCompetitionListResp, error)
		GetCompetitionInfo(ctx context.Context, in *GetCompetitionInfoReq, opts ...grpc.CallOption) (*GetCompetitionInfoResp, error)
		AddCompetition(ctx context.Context, in *AddCompetitionReq, opts ...grpc.CallOption) (*AddCompetitionResp, error)
		UpdateCompetition(ctx context.Context, in *UpdateCompetitionReq, opts ...grpc.CallOption) (*UpdateCompetitionResp, error)
		DeleteCompetition(ctx context.Context, in *DeleteCompetitionReq, opts ...grpc.CallOption) (*DeleteCompetitionResp, error)
		AttendCompetition(ctx context.Context, in *AttendCompetitionReq, opts ...grpc.CallOption) (*AttendCompetitionResp, error)
		GetCompetitionQuestionList(ctx context.Context, in *GetCompetitionQuestionListReq, opts ...grpc.CallOption) (*GetCompetitionQuestionListResp, error)
		GetCompetitionQuestionDetail(ctx context.Context, in *GetCompetitionQuestionDetailReq, opts ...grpc.CallOption) (*GetCompetitionQuestionDetailResp, error)
		SubmitCompetitionQuestion(ctx context.Context, in *SubmitCompetitionQuestionReq, opts ...grpc.CallOption) (*SubmitCompetitionQuestionResp, error)
		ContestAccessCheck(ctx context.Context, in *ContestAccessCheckReq, opts ...grpc.CallOption) (*ContestAccessCheckResp, error)
		GetCompetitionRankList(ctx context.Context, in *GetCompetitionRankListReq, opts ...grpc.CallOption) (*GetCompetitionRankListResp, error)
		IsUserInCompetition(ctx context.Context, in *IsUserInCompetitionReq, opts ...grpc.CallOption) (*IsUserInCompetitionResp, error)
	}

	defaultCompetition struct {
		cli zrpc.Client
	}
)

func NewCompetition(cli zrpc.Client) Competition {
	return &defaultCompetition{
		cli: cli,
	}
}

func (m *defaultCompetition) GetCompetitionList(ctx context.Context, in *GetCompetitionListReq, opts ...grpc.CallOption) (*GetCompetitionListResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.GetCompetitionList(ctx, in, opts...)
}

func (m *defaultCompetition) GetCompetitionInfo(ctx context.Context, in *GetCompetitionInfoReq, opts ...grpc.CallOption) (*GetCompetitionInfoResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.GetCompetitionInfo(ctx, in, opts...)
}

func (m *defaultCompetition) AddCompetition(ctx context.Context, in *AddCompetitionReq, opts ...grpc.CallOption) (*AddCompetitionResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.AddCompetition(ctx, in, opts...)
}

func (m *defaultCompetition) UpdateCompetition(ctx context.Context, in *UpdateCompetitionReq, opts ...grpc.CallOption) (*UpdateCompetitionResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.UpdateCompetition(ctx, in, opts...)
}

func (m *defaultCompetition) DeleteCompetition(ctx context.Context, in *DeleteCompetitionReq, opts ...grpc.CallOption) (*DeleteCompetitionResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.DeleteCompetition(ctx, in, opts...)
}

func (m *defaultCompetition) AttendCompetition(ctx context.Context, in *AttendCompetitionReq, opts ...grpc.CallOption) (*AttendCompetitionResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.AttendCompetition(ctx, in, opts...)
}

func (m *defaultCompetition) GetCompetitionQuestionList(ctx context.Context, in *GetCompetitionQuestionListReq, opts ...grpc.CallOption) (*GetCompetitionQuestionListResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.GetCompetitionQuestionList(ctx, in, opts...)
}

func (m *defaultCompetition) GetCompetitionQuestionDetail(ctx context.Context, in *GetCompetitionQuestionDetailReq, opts ...grpc.CallOption) (*GetCompetitionQuestionDetailResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.GetCompetitionQuestionDetail(ctx, in, opts...)
}

func (m *defaultCompetition) SubmitCompetitionQuestion(ctx context.Context, in *SubmitCompetitionQuestionReq, opts ...grpc.CallOption) (*SubmitCompetitionQuestionResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.SubmitCompetitionQuestion(ctx, in, opts...)
}

func (m *defaultCompetition) ContestAccessCheck(ctx context.Context, in *ContestAccessCheckReq, opts ...grpc.CallOption) (*ContestAccessCheckResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.ContestAccessCheck(ctx, in, opts...)
}

func (m *defaultCompetition) GetCompetitionRankList(ctx context.Context, in *GetCompetitionRankListReq, opts ...grpc.CallOption) (*GetCompetitionRankListResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.GetCompetitionRankList(ctx, in, opts...)
}

func (m *defaultCompetition) IsUserInCompetition(ctx context.Context, in *IsUserInCompetitionReq, opts ...grpc.CallOption) (*IsUserInCompetitionResp, error) {
	client := competition.NewCompetitionClient(m.cli.Conn())
	return client.IsUserInCompetition(ctx, in, opts...)
}
