// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: judge.proto

package server

import (
	"context"

	"backend/rpc/judge/internal/logic"
	"backend/rpc/judge/internal/svc"
	"backend/rpc/judge/pb/judge"
)

type JudgeServer struct {
	svcCtx *svc.ServiceContext
	judge.UnimplementedJudgeServer
}

func NewJudgeServer(svcCtx *svc.ServiceContext) *JudgeServer {
	return &JudgeServer{
		svcCtx: svcCtx,
	}
}

func (s *JudgeServer) Judge(ctx context.Context, in *judge.JudgeReq) (*judge.JudgeResp, error) {
	l := logic.NewJudgeLogic(ctx, s.svcCtx)
	return l.Judge(in)
}
