// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ExecResult struct {
	Output           string `json:"output"`
	TimeMilliseconds int64  `json:"time_milliseconds"`
	MemoryUsage      int64  `json:"memory_usage"`
	Accepted         bool   `json:"accepted"`
}

type GetUserInfoReq struct {
}

type GetUserInfoResp struct {
	UserId        uint64 `json:"user_id"`
	UserName      string `json:"user_name"`
	UserEmail     string `json:"user_email"`
	UserAvatarUrl string `json:"user_avatar_url"`
	UserProfile   string `json:"user_profile"`
	UserRole      string `json:"user_role"`
}

type JudgeReq struct {
	Code       string `json:"code"`
	Language   string `json:"language"`
	QuestionId uint64 `json:"question_id"`
}

type JudgeResp struct {
	Results []*ExecResult `json:"results"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type PaginationReq struct {
	Page     uint64            `json:"page"`
	PageSize uint64            `json:"page_size"`
	Filter   map[string]string `json:"filter"`
}

type PaginationResp struct {
	Questions []*QuestionBasicInfo `json:"questions"`
	Total     uint64               `json:"total"`
	Page      uint64               `json:"page"`
	PageSize  uint64               `json:"pagesize"`
}

type QuestionBasicInfo struct {
	Id         uint64   `json:"id"`
	Title      string   `json:"title"`
	Tags       []string `json:"tags"`
	Difficulty string   `json:difficulty`
	AcRate     float64  `json:ac_rate`
}

type QuestionInfoResponse struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type QuestionReq struct {
	Id uint64 `json:"id"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResp struct {
}
