// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: judge.proto

package server

import (
	"context"

	"backend/microservices/judge/internal/logic"
	"backend/microservices/judge/internal/svc"
	"backend/microservices/judge/pb/judge"
)

type JudgeServer struct {
	svcCtx *svc.ServiceContext
	judge.UnimplementedJudgeServer
}

func NewJudgeServer(svcCtx *svc.ServiceContext) *JudgeServer {
	return &JudgeServer{
		svcCtx: svcCtx,
	}
}

func (s *JudgeServer) Judge(ctx context.Context, in *judge.JudgeReq) (*judge.JudgeResp, error) {
	l := logic.NewJudgeLogic(ctx, s.svcCtx)
	return l.Judge(in)
}

func (s *JudgeServer) GetJudgeList(ctx context.Context, in *judge.GetJudgeListReq) (*judge.GetJudgeListResp, error) {
	l := logic.NewGetJudgeListLogic(ctx, s.svcCtx)
	return l.GetJudgeList(in)
}

func (s *JudgeServer) GetJudgeInfo(ctx context.Context, in *judge.GetJudgeInfoReq) (*judge.GetJudgeInfoResp, error) {
	l := logic.NewGetJudgeInfoLogic(ctx, s.svcCtx)
	return l.GetJudgeInfo(in)
}
