// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: competition.proto

package competition

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Competition_GetCompetitionList_FullMethodName           = "/competition.Competition/GetCompetitionList"
	Competition_GetCompetitionInfo_FullMethodName           = "/competition.Competition/GetCompetitionInfo"
	Competition_AddCompetition_FullMethodName               = "/competition.Competition/AddCompetition"
	Competition_UpdateCompetition_FullMethodName            = "/competition.Competition/UpdateCompetition"
	Competition_DeleteCompetition_FullMethodName            = "/competition.Competition/DeleteCompetition"
	Competition_AttendCompetition_FullMethodName            = "/competition.Competition/AttendCompetition"
	Competition_GetCompetitionQuestionList_FullMethodName   = "/competition.Competition/GetCompetitionQuestionList"
	Competition_GetCompetitionQuestionDetail_FullMethodName = "/competition.Competition/GetCompetitionQuestionDetail"
	Competition_SubmitCompetitionQuestion_FullMethodName    = "/competition.Competition/SubmitCompetitionQuestion"
	Competition_ContestAccessCheck_FullMethodName           = "/competition.Competition/ContestAccessCheck"
	Competition_GetCompetitionRankList_FullMethodName       = "/competition.Competition/GetCompetitionRankList"
	Competition_IsUserInCompetition_FullMethodName          = "/competition.Competition/IsUserInCompetition"
)

// CompetitionClient is the client API for Competition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompetitionClient interface {
	GetCompetitionList(ctx context.Context, in *GetCompetitionListReq, opts ...grpc.CallOption) (*GetCompetitionListResp, error)
	GetCompetitionInfo(ctx context.Context, in *GetCompetitionInfoReq, opts ...grpc.CallOption) (*GetCompetitionInfoResp, error)
	AddCompetition(ctx context.Context, in *AddCompetitionReq, opts ...grpc.CallOption) (*AddCompetitionResp, error)
	UpdateCompetition(ctx context.Context, in *UpdateCompetitionReq, opts ...grpc.CallOption) (*UpdateCompetitionResp, error)
	DeleteCompetition(ctx context.Context, in *DeleteCompetitionReq, opts ...grpc.CallOption) (*DeleteCompetitionResp, error)
	AttendCompetition(ctx context.Context, in *AttendCompetitionReq, opts ...grpc.CallOption) (*AttendCompetitionResp, error)
	GetCompetitionQuestionList(ctx context.Context, in *GetCompetitionQuestionListReq, opts ...grpc.CallOption) (*GetCompetitionQuestionListResp, error)
	GetCompetitionQuestionDetail(ctx context.Context, in *GetCompetitionQuestionDetailReq, opts ...grpc.CallOption) (*GetCompetitionQuestionDetailResp, error)
	SubmitCompetitionQuestion(ctx context.Context, in *SubmitCompetitionQuestionReq, opts ...grpc.CallOption) (*SubmitCompetitionQuestionResp, error)
	ContestAccessCheck(ctx context.Context, in *ContestAccessCheckReq, opts ...grpc.CallOption) (*ContestAccessCheckResp, error)
	GetCompetitionRankList(ctx context.Context, in *GetCompetitionRankListReq, opts ...grpc.CallOption) (*GetCompetitionRankListResp, error)
	IsUserInCompetition(ctx context.Context, in *IsUserInCompetitionReq, opts ...grpc.CallOption) (*IsUserInCompetitionResp, error)
}

type competitionClient struct {
	cc grpc.ClientConnInterface
}

func NewCompetitionClient(cc grpc.ClientConnInterface) CompetitionClient {
	return &competitionClient{cc}
}

func (c *competitionClient) GetCompetitionList(ctx context.Context, in *GetCompetitionListReq, opts ...grpc.CallOption) (*GetCompetitionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompetitionListResp)
	err := c.cc.Invoke(ctx, Competition_GetCompetitionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) GetCompetitionInfo(ctx context.Context, in *GetCompetitionInfoReq, opts ...grpc.CallOption) (*GetCompetitionInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompetitionInfoResp)
	err := c.cc.Invoke(ctx, Competition_GetCompetitionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) AddCompetition(ctx context.Context, in *AddCompetitionReq, opts ...grpc.CallOption) (*AddCompetitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCompetitionResp)
	err := c.cc.Invoke(ctx, Competition_AddCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) UpdateCompetition(ctx context.Context, in *UpdateCompetitionReq, opts ...grpc.CallOption) (*UpdateCompetitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCompetitionResp)
	err := c.cc.Invoke(ctx, Competition_UpdateCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) DeleteCompetition(ctx context.Context, in *DeleteCompetitionReq, opts ...grpc.CallOption) (*DeleteCompetitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCompetitionResp)
	err := c.cc.Invoke(ctx, Competition_DeleteCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) AttendCompetition(ctx context.Context, in *AttendCompetitionReq, opts ...grpc.CallOption) (*AttendCompetitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttendCompetitionResp)
	err := c.cc.Invoke(ctx, Competition_AttendCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) GetCompetitionQuestionList(ctx context.Context, in *GetCompetitionQuestionListReq, opts ...grpc.CallOption) (*GetCompetitionQuestionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompetitionQuestionListResp)
	err := c.cc.Invoke(ctx, Competition_GetCompetitionQuestionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) GetCompetitionQuestionDetail(ctx context.Context, in *GetCompetitionQuestionDetailReq, opts ...grpc.CallOption) (*GetCompetitionQuestionDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompetitionQuestionDetailResp)
	err := c.cc.Invoke(ctx, Competition_GetCompetitionQuestionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) SubmitCompetitionQuestion(ctx context.Context, in *SubmitCompetitionQuestionReq, opts ...grpc.CallOption) (*SubmitCompetitionQuestionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCompetitionQuestionResp)
	err := c.cc.Invoke(ctx, Competition_SubmitCompetitionQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) ContestAccessCheck(ctx context.Context, in *ContestAccessCheckReq, opts ...grpc.CallOption) (*ContestAccessCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContestAccessCheckResp)
	err := c.cc.Invoke(ctx, Competition_ContestAccessCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) GetCompetitionRankList(ctx context.Context, in *GetCompetitionRankListReq, opts ...grpc.CallOption) (*GetCompetitionRankListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompetitionRankListResp)
	err := c.cc.Invoke(ctx, Competition_GetCompetitionRankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitionClient) IsUserInCompetition(ctx context.Context, in *IsUserInCompetitionReq, opts ...grpc.CallOption) (*IsUserInCompetitionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsUserInCompetitionResp)
	err := c.cc.Invoke(ctx, Competition_IsUserInCompetition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompetitionServer is the server API for Competition service.
// All implementations must embed UnimplementedCompetitionServer
// for forward compatibility.
type CompetitionServer interface {
	GetCompetitionList(context.Context, *GetCompetitionListReq) (*GetCompetitionListResp, error)
	GetCompetitionInfo(context.Context, *GetCompetitionInfoReq) (*GetCompetitionInfoResp, error)
	AddCompetition(context.Context, *AddCompetitionReq) (*AddCompetitionResp, error)
	UpdateCompetition(context.Context, *UpdateCompetitionReq) (*UpdateCompetitionResp, error)
	DeleteCompetition(context.Context, *DeleteCompetitionReq) (*DeleteCompetitionResp, error)
	AttendCompetition(context.Context, *AttendCompetitionReq) (*AttendCompetitionResp, error)
	GetCompetitionQuestionList(context.Context, *GetCompetitionQuestionListReq) (*GetCompetitionQuestionListResp, error)
	GetCompetitionQuestionDetail(context.Context, *GetCompetitionQuestionDetailReq) (*GetCompetitionQuestionDetailResp, error)
	SubmitCompetitionQuestion(context.Context, *SubmitCompetitionQuestionReq) (*SubmitCompetitionQuestionResp, error)
	ContestAccessCheck(context.Context, *ContestAccessCheckReq) (*ContestAccessCheckResp, error)
	GetCompetitionRankList(context.Context, *GetCompetitionRankListReq) (*GetCompetitionRankListResp, error)
	IsUserInCompetition(context.Context, *IsUserInCompetitionReq) (*IsUserInCompetitionResp, error)
	mustEmbedUnimplementedCompetitionServer()
}

// UnimplementedCompetitionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompetitionServer struct{}

func (UnimplementedCompetitionServer) GetCompetitionList(context.Context, *GetCompetitionListReq) (*GetCompetitionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompetitionList not implemented")
}
func (UnimplementedCompetitionServer) GetCompetitionInfo(context.Context, *GetCompetitionInfoReq) (*GetCompetitionInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompetitionInfo not implemented")
}
func (UnimplementedCompetitionServer) AddCompetition(context.Context, *AddCompetitionReq) (*AddCompetitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCompetition not implemented")
}
func (UnimplementedCompetitionServer) UpdateCompetition(context.Context, *UpdateCompetitionReq) (*UpdateCompetitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompetition not implemented")
}
func (UnimplementedCompetitionServer) DeleteCompetition(context.Context, *DeleteCompetitionReq) (*DeleteCompetitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompetition not implemented")
}
func (UnimplementedCompetitionServer) AttendCompetition(context.Context, *AttendCompetitionReq) (*AttendCompetitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttendCompetition not implemented")
}
func (UnimplementedCompetitionServer) GetCompetitionQuestionList(context.Context, *GetCompetitionQuestionListReq) (*GetCompetitionQuestionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompetitionQuestionList not implemented")
}
func (UnimplementedCompetitionServer) GetCompetitionQuestionDetail(context.Context, *GetCompetitionQuestionDetailReq) (*GetCompetitionQuestionDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompetitionQuestionDetail not implemented")
}
func (UnimplementedCompetitionServer) SubmitCompetitionQuestion(context.Context, *SubmitCompetitionQuestionReq) (*SubmitCompetitionQuestionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCompetitionQuestion not implemented")
}
func (UnimplementedCompetitionServer) ContestAccessCheck(context.Context, *ContestAccessCheckReq) (*ContestAccessCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContestAccessCheck not implemented")
}
func (UnimplementedCompetitionServer) GetCompetitionRankList(context.Context, *GetCompetitionRankListReq) (*GetCompetitionRankListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompetitionRankList not implemented")
}
func (UnimplementedCompetitionServer) IsUserInCompetition(context.Context, *IsUserInCompetitionReq) (*IsUserInCompetitionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserInCompetition not implemented")
}
func (UnimplementedCompetitionServer) mustEmbedUnimplementedCompetitionServer() {}
func (UnimplementedCompetitionServer) testEmbeddedByValue()                     {}

// UnsafeCompetitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompetitionServer will
// result in compilation errors.
type UnsafeCompetitionServer interface {
	mustEmbedUnimplementedCompetitionServer()
}

func RegisterCompetitionServer(s grpc.ServiceRegistrar, srv CompetitionServer) {
	// If the following call pancis, it indicates UnimplementedCompetitionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Competition_ServiceDesc, srv)
}

func _Competition_GetCompetitionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).GetCompetitionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_GetCompetitionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).GetCompetitionList(ctx, req.(*GetCompetitionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_GetCompetitionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).GetCompetitionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_GetCompetitionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).GetCompetitionInfo(ctx, req.(*GetCompetitionInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_AddCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCompetitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).AddCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_AddCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).AddCompetition(ctx, req.(*AddCompetitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_UpdateCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompetitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).UpdateCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_UpdateCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).UpdateCompetition(ctx, req.(*UpdateCompetitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_DeleteCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCompetitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).DeleteCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_DeleteCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).DeleteCompetition(ctx, req.(*DeleteCompetitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_AttendCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttendCompetitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).AttendCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_AttendCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).AttendCompetition(ctx, req.(*AttendCompetitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_GetCompetitionQuestionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionQuestionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).GetCompetitionQuestionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_GetCompetitionQuestionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).GetCompetitionQuestionList(ctx, req.(*GetCompetitionQuestionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_GetCompetitionQuestionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionQuestionDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).GetCompetitionQuestionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_GetCompetitionQuestionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).GetCompetitionQuestionDetail(ctx, req.(*GetCompetitionQuestionDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_SubmitCompetitionQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCompetitionQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).SubmitCompetitionQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_SubmitCompetitionQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).SubmitCompetitionQuestion(ctx, req.(*SubmitCompetitionQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_ContestAccessCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContestAccessCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).ContestAccessCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_ContestAccessCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).ContestAccessCheck(ctx, req.(*ContestAccessCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_GetCompetitionRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitionRankListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).GetCompetitionRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_GetCompetitionRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).GetCompetitionRankList(ctx, req.(*GetCompetitionRankListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Competition_IsUserInCompetition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUserInCompetitionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitionServer).IsUserInCompetition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Competition_IsUserInCompetition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitionServer).IsUserInCompetition(ctx, req.(*IsUserInCompetitionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Competition_ServiceDesc is the grpc.ServiceDesc for Competition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Competition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "competition.Competition",
	HandlerType: (*CompetitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCompetitionList",
			Handler:    _Competition_GetCompetitionList_Handler,
		},
		{
			MethodName: "GetCompetitionInfo",
			Handler:    _Competition_GetCompetitionInfo_Handler,
		},
		{
			MethodName: "AddCompetition",
			Handler:    _Competition_AddCompetition_Handler,
		},
		{
			MethodName: "UpdateCompetition",
			Handler:    _Competition_UpdateCompetition_Handler,
		},
		{
			MethodName: "DeleteCompetition",
			Handler:    _Competition_DeleteCompetition_Handler,
		},
		{
			MethodName: "AttendCompetition",
			Handler:    _Competition_AttendCompetition_Handler,
		},
		{
			MethodName: "GetCompetitionQuestionList",
			Handler:    _Competition_GetCompetitionQuestionList_Handler,
		},
		{
			MethodName: "GetCompetitionQuestionDetail",
			Handler:    _Competition_GetCompetitionQuestionDetail_Handler,
		},
		{
			MethodName: "SubmitCompetitionQuestion",
			Handler:    _Competition_SubmitCompetitionQuestion_Handler,
		},
		{
			MethodName: "ContestAccessCheck",
			Handler:    _Competition_ContestAccessCheck_Handler,
		},
		{
			MethodName: "GetCompetitionRankList",
			Handler:    _Competition_GetCompetitionRankList_Handler,
		},
		{
			MethodName: "IsUserInCompetition",
			Handler:    _Competition_IsUserInCompetition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "competition.proto",
}
