// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type AddCompetitionReq struct {
	CompetitionInfo
	Password string `json:"password"`
}

type AddCompetitionResp struct {
}

type AddQuestionReq struct {
	QuestionInfo
}

type AddQuestionResp struct {
}

type AddUserReq struct {
	UserInfo
	Password string `json:"user_password"`
}

type AddUserResp struct {
}

type AdminGetCompetitionListReq struct {
	Page     int64             `json:"page"`
	PageSize int64             `json:"page_size"`
	Filter   map[string]string `json:"filter"`
}

type AdminGetCompetitionListResp struct {
	CompetitionList []*CompetitionInfo `json:"competition_list"`
	Total           int64              `json:"total"`
	Page            int64              `json:"page"`
	PageSize        int64              `json:"page_size"`
}

type AttendCompetitionReq struct {
	CompetitionId uint64 `json:"competition_id"`
	Password      string `json:"password"`
}

type AttendCompetitionResp struct {
}

type ChatReq struct {
	QuestionId uint64 `json:"question_id"`
	SessionId  string `json:"session_id"`
	Message    string `json:"message"`
}

type ChatResp struct {
}

type CodeCheckReq struct {
	QuestionId uint64 `json:"question_id"`
	Code       string `json:"code"`
}

type CodeCheckResp struct {
}

type CompetitionInfo struct {
	Id               uint64                 `json:"id,optional,omitempty"`
	Name             string                 `json:"name,optional,omitempty"`
	Description      string                 `json:"description,optional,omitempty"`
	StartTime        string                 `json:"start_time,optional,omitempty"`
	EndTime          string                 `json:"end_time,optional,omitempty"`
	Questions        []*CompetitionQuestion `json:"questions,optional,omitempty"`
	CompetitionType  string                 `json:"competition_type,optional,omitempty"`
	PasswordRequired bool                   `json:"password_required,optional"`
}

type CompetitionQuestion struct {
	Qid string `json:"qid"`
	Id  uint64 `json:"id"`
}

type CompetitionScore struct {
	UserId       uint64        `json:"user_id"`
	Username     string        `json:"username"`
	TotalScore   float64       `json:"total_score"`
	ScoreDetails []ScoreDetail `json:"score_details"`
}

type DeleteCompetitionReq struct {
	Id uint64 `json:"id"`
}

type DeleteCompetitionResp struct {
}

type DeleteQuestionReq struct {
	Id uint64 `json:"id"`
}

type DeleteQuestionResp struct {
}

type DeleteUserReq struct {
	UserId uint64 `json:"user_id"`
}

type DeleteUserResp struct {
}

type ExecDetail struct {
	Output           string `json:"output"`            // 程序输出
	TimeMilliseconds int64  `json:"time_milliseconds"` // 运行时间，单位为毫秒（Milliseconds）
	MemoryUsage      int64  `json:"memory_usage_kb"`   // 占用内存，单位为KB
	Timeout          bool   `json:"timeout"`           // 是否超时
	MemoryOut        bool   `json:"memory_out"`        // 是否内存超限
	RuntimeError     bool   `json:"runtime_error"`     // 是否运行时错误
	StackOverflow    bool   `json:"stack_overflow"`    // 是否栈溢出
	Accepted         bool   `json:"accepted"`          // 是否通过
}

type GetCompetitionInfoReq struct {
	CompetitionId uint64 `json:"competition_id"`
}

type GetCompetitionInfoResp struct {
	CompetitionInfo
}

type GetCompetitionListReq struct {
	Page     int64             `json:"page"`
	PageSize int64             `json:"page_size"`
	Filter   map[string]string `json:"filter"`
}

type GetCompetitionListResp struct {
	CompetitionList []*CompetitionInfo `json:"competition_list"`
	Total           int64              `json:"total"`
	Page            int64              `json:"page"`
	PageSize        int64              `json:"page_size"`
}

type GetCompetitionQuestionDetailReq struct {
	CompetitionId uint64 `json:"competition_id"`
	Qid           string `json:"qid"`
}

type GetCompetitionQuestionDetailResp struct {
	QuestionDetailInfo
}

type GetCompetitionQuestionListReq struct {
	CompetitionId uint64 `json:"competition_id"`
}

type GetCompetitionQuestionListResp struct {
	QuestionList []QuestionBasicInfo `json:"question_list"`
}

type GetCompetitionRankListReq struct {
	CompetitionId uint64 `json:"competition_id"`
}

type GetCompetitionRankListResp struct {
	RankList []*CompetitionScore `json:"rank_list"`
}

type GetJudgeListReq struct {
	Page     uint64 `json:"page"`
	PageSize uint64 `json:"page_size"`
}

type GetJudgeListResp struct {
	JudgeList []*JudgeInfo `json:"judge_list"`
	Total     uint64       `json:"total"`
	Page      uint64       `json:"page"`
	PageSize  uint64       `json:"page_size"`
}

type GetPublicInfoReq struct {
	UserId uint64 `json:"user_id"`
}

type GetPublicInfoResp struct {
	UserInfo
}

type GetPublicQuestionListReq struct {
	Page     int64             `json:"page"`
	PageSize int64             `json:"page_size"`
	Filter   map[string]string `json:"filter"`
}

type GetPublicQuestionListResp struct {
	QuestionInfo []*QuestionInfo `json:"questions"`
	Total        int64           `json:"total"`
	Page         int64           `json:"page"`
	PageSize     int64           `json:"page_size"`
}

type GetQuestionBasicInfoReq struct {
	Id uint64 `json:"id"`
}

type GetQuestionBasicInfoResp struct {
	QuestionInfo
}

type GetQuestionListReq struct {
	Page     int64             `json:"page"`
	PageSize int64             `json:"page_size"`
	Filter   map[string]string `json:"filter"`
}

type GetQuestionListResp struct {
	QuestionInfo []*QuestionInfo `json:"questions"`
	Total        int64           `json:"total"`
	Page         int64           `json:"page"`
	PageSize     int64           `json:"page_size"`
}

type GetQuestionSessionsReq struct {
	QuestionId uint64 `json:"question_id"`
}

type GetQuestionSessionsResp struct {
}

type GetSessionMessageHistoryReq struct {
	SessionId string `json:"session_id"`
}

type GetSessionMessageHistoryResp struct {
}

type GetUserInfoReq struct {
}

type GetUserInfoResp struct {
	UserInfo
}

type GetUserListReq struct {
	Page     int64             `json:"page"`
	PageSize int64             `json:"page_size"`
	Filter   map[string]string `json:"filter"`
}

type GetUserListResp struct {
	UserInfo []*UserInfo `json:"users"`
	Total    int64       `json:"total"`
	Page     int64       `json:"page"`
	PageSize int64       `json:"page_size"`
}

type JudgeCase struct {
	Input  string `json:"input,optional"`
	Output string `json:"output,optional"`
}

type JudgeConfig struct {
	MemoryLimitMib     int64 `json:"memory_limit_mib,optional"`
	StackLimitMib      int64 `json:"stack_limit_mib,optional"`
	TimeoutMillisecond int64 `json:"timeout_millisecond,optional"`
}

type JudgeConfigComp struct {
	MemoryLimitMib     int64 `json:"memory_limit_mib,optional"`
	StackLimitMib      int64 `json:"stack_limit_mib,optional"`
	TimeoutMillisecond int64 `json:"timeout_millisecond,optional"`
}

type JudgeInfo struct {
	JudgeId    uint64 `json:"judge_id"`
	UserId     uint64 `json:"user_id"`
	QuestionId uint64 `json:"question_id"`
	Language   string `json:"language"`
	Code       string `json:"code"`
	ExecResult string `json:"exec_result"`
	Accepted   bool   `json:"accepted"`
	CreateAt   string `json:"create_at"`
	UpdateAt   string `json:"update_at"`
}

type JudgeReq struct {
	Code       string `json:"code"`
	Language   string `json:"language"`
	QuestionId uint64 `json:"question_id"`
}

type JudgeResp struct {
	ExecDetails        []*ExecDetail `json:"exec_details"`
	CompileError       bool          `json:"compile_error"`
	CompileErrorOutput string        `json:"compile_error_output"`
}

type JudgeResult struct {
	ExecDetails        []*ExecDetail `json:"exec_details"`         // 每个测试用例的执行结果
	CompileError       bool          `json:"compile_error"`        // 是否编译错误
	CompileErrorOutput string        `json:"compile_error_output"` // 错误输出
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type QuestionBasicInfo struct {
	Qid   string `json:"qid"`
	Title string `json:"title"`
}

type QuestionDetailInfo struct {
	Qid         string          `json:"qid"`
	Title       string          `json:"title"`
	Content     string          `json:"content"`
	JudgeConfig JudgeConfigComp `json:"judge_config"`
}

type QuestionInfo struct {
	Id           uint64       `json:"id,optional,omitempty"`
	Title        string       `json:"title,optional,omitempty"`
	Content      string       `json:"content,optional,omitempty"`
	Tags         []string     `json:"tags,optional,omitempty"`
	Difficulty   string       `json:"difficulty,optional,omitempty"`
	SubmitNum    uint64       `json:"submit_num,optional"`
	AcceptedNum  uint64       `json:"accepted_num,optional"`
	JudgeCase    []*JudgeCase `json:"judge_case,optional,omitempty"`
	JudgeConfig  *JudgeConfig `json:"judge_config,optional,omitempty"`
	VisibleScope string       `json:"visible_scope,optional,omitempty"`
	CreateAt     string       `json:"create_at,optional,omitempty"`
	UpdateAt     string       `json:"update_at,optional,omitempty"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResp struct {
}

type ScoreDetail struct {
	Qid   string  `json:"qid"`
	Score float64 `json:"score"`
}

type Session struct {
	SessionId  string `json:"session_id"`
	QuestionId uint64 `json:"question_id"`
	Title      string `json:"title"`
}

type SubmitCompetitionQuestionReq struct {
	CompetitionId uint64 `json:"competition_id"`
	Qid           string `json:"qid"`
	Code          string `json:"code"`
	Language      string `json:"language"`
}

type SubmitCompetitionQuestionResp struct {
	JudgeResult
}

type UpdateCompetitionReq struct {
	CompetitionInfo
	Password string `json:"password"`
}

type UpdateCompetitionResp struct {
}

type UpdatePersonalInfoReq struct {
	UserInfo
	AvatarBase64 string `json:"avatar_base64,optional"`
}

type UpdatePersonalInfoResp struct {
}

type UpdateQuestionReq struct {
	QuestionInfo
}

type UpdateQuestionResp struct {
}

type UpdateUserPasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type UpdateUserPasswordResp struct {
}

type UpdateUserReq struct {
	UserInfo
	Password     string `json:"user_password,optional"`
	AvatarBase64 string `json:"avatar_base64,optional"`
}

type UpdateUserResp struct {
}

type UserInfo struct {
	UserId        uint64 `json:"user_id,optional,omitempty"`
	UserName      string `json:"user_name,optional,omitempty"`
	UserEmail     string `json:"user_email,optional,omitempty"`
	UserAvatarUrl string `json:"user_avatar_url,optional,omitempty"`
	UserProfile   string `json:"user_profile,optional,omitempty"`
	UserRole      string `json:"user_role,optional,omitempty"`
	CreateAt      string `json:"create_at,optional,omitempty"`
	UpdateAt      string `json:"update_at,optional,omitempty"`
}
