// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: question.proto

package server

import (
	"context"

	"backend/rpc/question/internal/logic"
	"backend/rpc/question/internal/svc"
	"backend/rpc/question/pb/question"
)

type QuestionServer struct {
	svcCtx *svc.ServiceContext
	question.UnimplementedQuestionServer
}

func NewQuestionServer(svcCtx *svc.ServiceContext) *QuestionServer {
	return &QuestionServer{
		svcCtx: svcCtx,
	}
}

func (s *QuestionServer) GetQuestionInfo(ctx context.Context, in *question.QuestionRequest) (*question.QuestionInfoResponse, error) {
	l := logic.NewGetQuestionInfoLogic(ctx, s.svcCtx)
	return l.GetQuestionInfo(in)
}

func (s *QuestionServer) GetQuestionJudgeCase(ctx context.Context, in *question.QuestionRequest) (*question.QuestionJudgeCaseResponse, error) {
	l := logic.NewGetQuestionJudgeCaseLogic(ctx, s.svcCtx)
	return l.GetQuestionJudgeCase(in)
}

func (s *QuestionServer) Pagination(ctx context.Context, in *question.PaginationRequest) (*question.PaginationResponse, error) {
	l := logic.NewPaginationLogic(ctx, s.svcCtx)
	return l.Pagination(in)
}
