"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QuestionInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    DIFFICULTY_FIELD_NUMBER: builtins.int
    SUBMIT_NUM_FIELD_NUMBER: builtins.int
    ACCEPTED_NUM_FIELD_NUMBER: builtins.int
    JUDGE_CASE_FIELD_NUMBER: builtins.int
    JUDGE_CONFIG_FIELD_NUMBER: builtins.int
    VISIBLE_SCOPE_FIELD_NUMBER: builtins.int
    CREATE_AT_FIELD_NUMBER: builtins.int
    UPDATE_AT_FIELD_NUMBER: builtins.int
    id: builtins.int
    title: builtins.str
    content: builtins.str
    tags: builtins.str
    difficulty: builtins.str
    submit_num: builtins.int
    accepted_num: builtins.int
    judge_case: builtins.str
    judge_config: builtins.str
    visible_scope: builtins.str
    create_at: builtins.str
    update_at: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        title: builtins.str = ...,
        content: builtins.str = ...,
        tags: builtins.str = ...,
        difficulty: builtins.str = ...,
        submit_num: builtins.int = ...,
        accepted_num: builtins.int = ...,
        judge_case: builtins.str = ...,
        judge_config: builtins.str = ...,
        visible_scope: builtins.str = ...,
        create_at: builtins.str = ...,
        update_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accepted_num", b"accepted_num", "content", b"content", "create_at", b"create_at", "difficulty", b"difficulty", "id", b"id", "judge_case", b"judge_case", "judge_config", b"judge_config", "submit_num", b"submit_num", "tags", b"tags", "title", b"title", "update_at", b"update_at", "visible_scope", b"visible_scope"]) -> None: ...

global___QuestionInfo = QuestionInfo

@typing.final
class AddQuestionReq(google.protobuf.message.Message):
    """添加题目"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUESTION_INFO_FIELD_NUMBER: builtins.int
    @property
    def question_info(self) -> global___QuestionInfo: ...
    def __init__(
        self,
        *,
        question_info: global___QuestionInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["question_info", b"question_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["question_info", b"question_info"]) -> None: ...

global___AddQuestionReq = AddQuestionReq

@typing.final
class AddQuestionResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AddQuestionResp = AddQuestionResp

@typing.final
class DeleteQuestionReq(google.protobuf.message.Message):
    """删除题目"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___DeleteQuestionReq = DeleteQuestionReq

@typing.final
class DeleteQuestionResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteQuestionResp = DeleteQuestionResp

@typing.final
class UpdateQuestionReq(google.protobuf.message.Message):
    """更新题目"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUESTION_INFO_FIELD_NUMBER: builtins.int
    @property
    def question_info(self) -> global___QuestionInfo: ...
    def __init__(
        self,
        *,
        question_info: global___QuestionInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["question_info", b"question_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["question_info", b"question_info"]) -> None: ...

global___UpdateQuestionReq = UpdateQuestionReq

@typing.final
class UpdateQuestionResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateQuestionResp = UpdateQuestionResp

@typing.final
class GetQuestionInfoReq(google.protobuf.message.Message):
    """获取题目信息（单道题目）"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FilterEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    COL_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def filter(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def col(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        filter: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        col: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["col", b"col", "filter", b"filter", "id", b"id"]) -> None: ...

global___GetQuestionInfoReq = GetQuestionInfoReq

@typing.final
class GetQuestionInfoResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUESTION_INFO_FIELD_NUMBER: builtins.int
    @property
    def question_info(self) -> global___QuestionInfo: ...
    def __init__(
        self,
        *,
        question_info: global___QuestionInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["question_info", b"question_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["question_info", b"question_info"]) -> None: ...

global___GetQuestionInfoResp = GetQuestionInfoResp

@typing.final
class GetQuestionListReq(google.protobuf.message.Message):
    """获取题目列表"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FilterEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    COL_FIELD_NUMBER: builtins.int
    page: builtins.int
    page_size: builtins.int
    @property
    def filter(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def col(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        filter: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        col: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["col", b"col", "filter", b"filter", "page", b"page", "page_size", b"page_size"]) -> None: ...

global___GetQuestionListReq = GetQuestionListReq

@typing.final
class GetQuestionListResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUESTION_LIST_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    total: builtins.int
    page: builtins.int
    page_size: builtins.int
    @property
    def question_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___QuestionInfo]: ...
    def __init__(
        self,
        *,
        question_list: collections.abc.Iterable[global___QuestionInfo] | None = ...,
        total: builtins.int = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page", b"page", "page_size", b"page_size", "question_list", b"question_list", "total", b"total"]) -> None: ...

global___GetQuestionListResp = GetQuestionListResp

@typing.final
class GetQuestionJudgeCaseReq(google.protobuf.message.Message):
    """获取题目评测用例"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetQuestionJudgeCaseReq = GetQuestionJudgeCaseReq

@typing.final
class GetQuestionJudgeCaseResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JUDGE_CASE_FIELD_NUMBER: builtins.int
    judge_case: builtins.str
    def __init__(
        self,
        *,
        judge_case: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["judge_case", b"judge_case"]) -> None: ...

global___GetQuestionJudgeCaseResp = GetQuestionJudgeCaseResp

@typing.final
class GetQuestionJudgeConfigReq(google.protobuf.message.Message):
    """获取题目评测配置"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetQuestionJudgeConfigReq = GetQuestionJudgeConfigReq

@typing.final
class GetQuestionJudgeConfigResp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JUDGE_CONFIG_FIELD_NUMBER: builtins.int
    judge_config: builtins.str
    def __init__(
        self,
        *,
        judge_config: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["judge_config", b"judge_config"]) -> None: ...

global___GetQuestionJudgeConfigResp = GetQuestionJudgeConfigResp
