"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import question_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class QuestionStub:
    """题目服务"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    AddQuestion: grpc.UnaryUnaryMultiCallable[
        question_pb2.AddQuestionReq,
        question_pb2.AddQuestionResp,
    ]

    DeleteQuestion: grpc.UnaryUnaryMultiCallable[
        question_pb2.DeleteQuestionReq,
        question_pb2.DeleteQuestionResp,
    ]

    UpdateQuestion: grpc.UnaryUnaryMultiCallable[
        question_pb2.UpdateQuestionReq,
        question_pb2.UpdateQuestionResp,
    ]

    GetQuestionInfo: grpc.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionInfoReq,
        question_pb2.GetQuestionInfoResp,
    ]

    GetQuestionList: grpc.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionListReq,
        question_pb2.GetQuestionListResp,
    ]

    GetQuestionJudgeCase: grpc.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionJudgeCaseReq,
        question_pb2.GetQuestionJudgeCaseResp,
    ]

    GetQuestionJudgeConfig: grpc.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionJudgeConfigReq,
        question_pb2.GetQuestionJudgeConfigResp,
    ]

class QuestionAsyncStub:
    """题目服务"""

    AddQuestion: grpc.aio.UnaryUnaryMultiCallable[
        question_pb2.AddQuestionReq,
        question_pb2.AddQuestionResp,
    ]

    DeleteQuestion: grpc.aio.UnaryUnaryMultiCallable[
        question_pb2.DeleteQuestionReq,
        question_pb2.DeleteQuestionResp,
    ]

    UpdateQuestion: grpc.aio.UnaryUnaryMultiCallable[
        question_pb2.UpdateQuestionReq,
        question_pb2.UpdateQuestionResp,
    ]

    GetQuestionInfo: grpc.aio.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionInfoReq,
        question_pb2.GetQuestionInfoResp,
    ]

    GetQuestionList: grpc.aio.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionListReq,
        question_pb2.GetQuestionListResp,
    ]

    GetQuestionJudgeCase: grpc.aio.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionJudgeCaseReq,
        question_pb2.GetQuestionJudgeCaseResp,
    ]

    GetQuestionJudgeConfig: grpc.aio.UnaryUnaryMultiCallable[
        question_pb2.GetQuestionJudgeConfigReq,
        question_pb2.GetQuestionJudgeConfigResp,
    ]

class QuestionServicer(metaclass=abc.ABCMeta):
    """题目服务"""

    @abc.abstractmethod
    def AddQuestion(
        self,
        request: question_pb2.AddQuestionReq,
        context: _ServicerContext,
    ) -> typing.Union[question_pb2.AddQuestionResp, collections.abc.Awaitable[question_pb2.AddQuestionResp]]: ...

    @abc.abstractmethod
    def DeleteQuestion(
        self,
        request: question_pb2.DeleteQuestionReq,
        context: _ServicerContext,
    ) -> typing.Union[question_pb2.DeleteQuestionResp, collections.abc.Awaitable[question_pb2.DeleteQuestionResp]]: ...

    @abc.abstractmethod
    def UpdateQuestion(
        self,
        request: question_pb2.UpdateQuestionReq,
        context: _ServicerContext,
    ) -> typing.Union[question_pb2.UpdateQuestionResp, collections.abc.Awaitable[question_pb2.UpdateQuestionResp]]: ...

    @abc.abstractmethod
    def GetQuestionInfo(
        self,
        request: question_pb2.GetQuestionInfoReq,
        context: _ServicerContext,
    ) -> typing.Union[question_pb2.GetQuestionInfoResp, collections.abc.Awaitable[question_pb2.GetQuestionInfoResp]]: ...

    @abc.abstractmethod
    def GetQuestionList(
        self,
        request: question_pb2.GetQuestionListReq,
        context: _ServicerContext,
    ) -> typing.Union[question_pb2.GetQuestionListResp, collections.abc.Awaitable[question_pb2.GetQuestionListResp]]: ...

    @abc.abstractmethod
    def GetQuestionJudgeCase(
        self,
        request: question_pb2.GetQuestionJudgeCaseReq,
        context: _ServicerContext,
    ) -> typing.Union[question_pb2.GetQuestionJudgeCaseResp, collections.abc.Awaitable[question_pb2.GetQuestionJudgeCaseResp]]: ...

    @abc.abstractmethod
    def GetQuestionJudgeConfig(
        self,
        request: question_pb2.GetQuestionJudgeConfigReq,
        context: _ServicerContext,
    ) -> typing.Union[question_pb2.GetQuestionJudgeConfigResp, collections.abc.Awaitable[question_pb2.GetQuestionJudgeConfigResp]]: ...

def add_QuestionServicer_to_server(servicer: QuestionServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
