# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import question_pb2 as question__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in question_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class QuestionStub(object):
    """题目服务"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddQuestion = channel.unary_unary(
            "/question.Question/AddQuestion",
            request_serializer=question__pb2.AddQuestionReq.SerializeToString,
            response_deserializer=question__pb2.AddQuestionResp.FromString,
            _registered_method=True,
        )
        self.DeleteQuestion = channel.unary_unary(
            "/question.Question/DeleteQuestion",
            request_serializer=question__pb2.DeleteQuestionReq.SerializeToString,
            response_deserializer=question__pb2.DeleteQuestionResp.FromString,
            _registered_method=True,
        )
        self.UpdateQuestion = channel.unary_unary(
            "/question.Question/UpdateQuestion",
            request_serializer=question__pb2.UpdateQuestionReq.SerializeToString,
            response_deserializer=question__pb2.UpdateQuestionResp.FromString,
            _registered_method=True,
        )
        self.GetQuestionInfo = channel.unary_unary(
            "/question.Question/GetQuestionInfo",
            request_serializer=question__pb2.GetQuestionInfoReq.SerializeToString,
            response_deserializer=question__pb2.GetQuestionInfoResp.FromString,
            _registered_method=True,
        )
        self.GetQuestionList = channel.unary_unary(
            "/question.Question/GetQuestionList",
            request_serializer=question__pb2.GetQuestionListReq.SerializeToString,
            response_deserializer=question__pb2.GetQuestionListResp.FromString,
            _registered_method=True,
        )
        self.GetQuestionJudgeCase = channel.unary_unary(
            "/question.Question/GetQuestionJudgeCase",
            request_serializer=question__pb2.GetQuestionJudgeCaseReq.SerializeToString,
            response_deserializer=question__pb2.GetQuestionJudgeCaseResp.FromString,
            _registered_method=True,
        )
        self.GetQuestionJudgeConfig = channel.unary_unary(
            "/question.Question/GetQuestionJudgeConfig",
            request_serializer=question__pb2.GetQuestionJudgeConfigReq.SerializeToString,
            response_deserializer=question__pb2.GetQuestionJudgeConfigResp.FromString,
            _registered_method=True,
        )


class QuestionServicer(object):
    """题目服务"""

    def AddQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQuestionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQuestionList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQuestionJudgeCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQuestionJudgeConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QuestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AddQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.AddQuestion,
            request_deserializer=question__pb2.AddQuestionReq.FromString,
            response_serializer=question__pb2.AddQuestionResp.SerializeToString,
        ),
        "DeleteQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteQuestion,
            request_deserializer=question__pb2.DeleteQuestionReq.FromString,
            response_serializer=question__pb2.DeleteQuestionResp.SerializeToString,
        ),
        "UpdateQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateQuestion,
            request_deserializer=question__pb2.UpdateQuestionReq.FromString,
            response_serializer=question__pb2.UpdateQuestionResp.SerializeToString,
        ),
        "GetQuestionInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetQuestionInfo,
            request_deserializer=question__pb2.GetQuestionInfoReq.FromString,
            response_serializer=question__pb2.GetQuestionInfoResp.SerializeToString,
        ),
        "GetQuestionList": grpc.unary_unary_rpc_method_handler(
            servicer.GetQuestionList,
            request_deserializer=question__pb2.GetQuestionListReq.FromString,
            response_serializer=question__pb2.GetQuestionListResp.SerializeToString,
        ),
        "GetQuestionJudgeCase": grpc.unary_unary_rpc_method_handler(
            servicer.GetQuestionJudgeCase,
            request_deserializer=question__pb2.GetQuestionJudgeCaseReq.FromString,
            response_serializer=question__pb2.GetQuestionJudgeCaseResp.SerializeToString,
        ),
        "GetQuestionJudgeConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetQuestionJudgeConfig,
            request_deserializer=question__pb2.GetQuestionJudgeConfigReq.FromString,
            response_serializer=question__pb2.GetQuestionJudgeConfigResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "question.Question", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("question.Question", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Question(object):
    """题目服务"""

    @staticmethod
    def AddQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/question.Question/AddQuestion",
            question__pb2.AddQuestionReq.SerializeToString,
            question__pb2.AddQuestionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/question.Question/DeleteQuestion",
            question__pb2.DeleteQuestionReq.SerializeToString,
            question__pb2.DeleteQuestionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/question.Question/UpdateQuestion",
            question__pb2.UpdateQuestionReq.SerializeToString,
            question__pb2.UpdateQuestionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetQuestionInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/question.Question/GetQuestionInfo",
            question__pb2.GetQuestionInfoReq.SerializeToString,
            question__pb2.GetQuestionInfoResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetQuestionList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/question.Question/GetQuestionList",
            question__pb2.GetQuestionListReq.SerializeToString,
            question__pb2.GetQuestionListResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetQuestionJudgeCase(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/question.Question/GetQuestionJudgeCase",
            question__pb2.GetQuestionJudgeCaseReq.SerializeToString,
            question__pb2.GetQuestionJudgeCaseResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetQuestionJudgeConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/question.Question/GetQuestionJudgeConfig",
            question__pb2.GetQuestionJudgeConfigReq.SerializeToString,
            question__pb2.GetQuestionJudgeConfigResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
