// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: question.proto

package questionclient

import (
	"context"

	"backend/microservices/question/pb/question"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAcceptedNumReq          = question.AddAcceptedNumReq
	AddAcceptedNumResp         = question.AddAcceptedNumResp
	AddQuestionReq             = question.AddQuestionReq
	AddQuestionResp            = question.AddQuestionResp
	AddSubmitNumReq            = question.AddSubmitNumReq
	AddSubmitNumResp           = question.AddSubmitNumResp
	DeleteQuestionReq          = question.DeleteQuestionReq
	DeleteQuestionResp         = question.DeleteQuestionResp
	GetQuestionInfoReq         = question.GetQuestionInfoReq
	GetQuestionInfoResp        = question.GetQuestionInfoResp
	GetQuestionJudgeCaseReq    = question.GetQuestionJudgeCaseReq
	GetQuestionJudgeCaseResp   = question.GetQuestionJudgeCaseResp
	GetQuestionJudgeConfigReq  = question.GetQuestionJudgeConfigReq
	GetQuestionJudgeConfigResp = question.GetQuestionJudgeConfigResp
	GetQuestionListReq         = question.GetQuestionListReq
	GetQuestionListResp        = question.GetQuestionListResp
	QuestionInfo               = question.QuestionInfo
	UpdateQuestionReq          = question.UpdateQuestionReq
	UpdateQuestionResp         = question.UpdateQuestionResp

	Question interface {
		AddQuestion(ctx context.Context, in *AddQuestionReq, opts ...grpc.CallOption) (*AddQuestionResp, error)
		DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionResp, error)
		UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionResp, error)
		GetQuestionInfo(ctx context.Context, in *GetQuestionInfoReq, opts ...grpc.CallOption) (*GetQuestionInfoResp, error)
		GetQuestionList(ctx context.Context, in *GetQuestionListReq, opts ...grpc.CallOption) (*GetQuestionListResp, error)
		GetQuestionJudgeCase(ctx context.Context, in *GetQuestionJudgeCaseReq, opts ...grpc.CallOption) (*GetQuestionJudgeCaseResp, error)
		GetQuestionJudgeConfig(ctx context.Context, in *GetQuestionJudgeConfigReq, opts ...grpc.CallOption) (*GetQuestionJudgeConfigResp, error)
		AddSubmitNum(ctx context.Context, in *AddSubmitNumReq, opts ...grpc.CallOption) (*AddSubmitNumResp, error)
		AddAcceptedNum(ctx context.Context, in *AddAcceptedNumReq, opts ...grpc.CallOption) (*AddAcceptedNumResp, error)
	}

	defaultQuestion struct {
		cli zrpc.Client
	}
)

func NewQuestion(cli zrpc.Client) Question {
	return &defaultQuestion{
		cli: cli,
	}
}

func (m *defaultQuestion) AddQuestion(ctx context.Context, in *AddQuestionReq, opts ...grpc.CallOption) (*AddQuestionResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.AddQuestion(ctx, in, opts...)
}

func (m *defaultQuestion) DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.DeleteQuestion(ctx, in, opts...)
}

func (m *defaultQuestion) UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.UpdateQuestion(ctx, in, opts...)
}

func (m *defaultQuestion) GetQuestionInfo(ctx context.Context, in *GetQuestionInfoReq, opts ...grpc.CallOption) (*GetQuestionInfoResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.GetQuestionInfo(ctx, in, opts...)
}

func (m *defaultQuestion) GetQuestionList(ctx context.Context, in *GetQuestionListReq, opts ...grpc.CallOption) (*GetQuestionListResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.GetQuestionList(ctx, in, opts...)
}

func (m *defaultQuestion) GetQuestionJudgeCase(ctx context.Context, in *GetQuestionJudgeCaseReq, opts ...grpc.CallOption) (*GetQuestionJudgeCaseResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.GetQuestionJudgeCase(ctx, in, opts...)
}

func (m *defaultQuestion) GetQuestionJudgeConfig(ctx context.Context, in *GetQuestionJudgeConfigReq, opts ...grpc.CallOption) (*GetQuestionJudgeConfigResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.GetQuestionJudgeConfig(ctx, in, opts...)
}

func (m *defaultQuestion) AddSubmitNum(ctx context.Context, in *AddSubmitNumReq, opts ...grpc.CallOption) (*AddSubmitNumResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.AddSubmitNum(ctx, in, opts...)
}

func (m *defaultQuestion) AddAcceptedNum(ctx context.Context, in *AddAcceptedNumReq, opts ...grpc.CallOption) (*AddAcceptedNumResp, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.AddAcceptedNum(ctx, in, opts...)
}
