// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: judge.proto

package judgeclient

import (
	"context"

	"backend/rpc/judge/pb/judge"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecResult = judge.ExecResult
	JudgeReq   = judge.JudgeReq
	JudgeResp  = judge.JudgeResp

	Judge interface {
		Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error)
	}

	defaultJudge struct {
		cli zrpc.Client
	}
)

func NewJudge(cli zrpc.Client) Judge {
	return &defaultJudge{
		cli: cli,
	}
}

func (m *defaultJudge) Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error) {
	client := judge.NewJudgeClient(m.cli.Conn())
	return client.Judge(ctx, in, opts...)
}
