// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: competition.proto

package server

import (
	"context"

	"backend/microservices/competition/internal/logic"
	"backend/microservices/competition/internal/svc"
	"backend/microservices/competition/pb/competition"
)

type CompetitionServer struct {
	svcCtx *svc.ServiceContext
	competition.UnimplementedCompetitionServer
}

func NewCompetitionServer(svcCtx *svc.ServiceContext) *CompetitionServer {
	return &CompetitionServer{
		svcCtx: svcCtx,
	}
}

func (s *CompetitionServer) GetCompetitionList(ctx context.Context, in *competition.GetCompetitionListReq) (*competition.GetCompetitionListResp, error) {
	l := logic.NewGetCompetitionListLogic(ctx, s.svcCtx)
	return l.GetCompetitionList(in)
}

func (s *CompetitionServer) GetCompetitionInfo(ctx context.Context, in *competition.GetCompetitionInfoReq) (*competition.GetCompetitionInfoResp, error) {
	l := logic.NewGetCompetitionInfoLogic(ctx, s.svcCtx)
	return l.GetCompetitionInfo(in)
}

func (s *CompetitionServer) AddCompetition(ctx context.Context, in *competition.AddCompetitionReq) (*competition.AddCompetitionResp, error) {
	l := logic.NewAddCompetitionLogic(ctx, s.svcCtx)
	return l.AddCompetition(in)
}

func (s *CompetitionServer) UpdateCompetition(ctx context.Context, in *competition.UpdateCompetitionReq) (*competition.UpdateCompetitionResp, error) {
	l := logic.NewUpdateCompetitionLogic(ctx, s.svcCtx)
	return l.UpdateCompetition(in)
}

func (s *CompetitionServer) DeleteCompetition(ctx context.Context, in *competition.DeleteCompetitionReq) (*competition.DeleteCompetitionResp, error) {
	l := logic.NewDeleteCompetitionLogic(ctx, s.svcCtx)
	return l.DeleteCompetition(in)
}

func (s *CompetitionServer) AttendCompetition(ctx context.Context, in *competition.AttendCompetitionReq) (*competition.AttendCompetitionResp, error) {
	l := logic.NewAttendCompetitionLogic(ctx, s.svcCtx)
	return l.AttendCompetition(in)
}

func (s *CompetitionServer) GetCompetitionQuestionList(ctx context.Context, in *competition.GetCompetitionQuestionListReq) (*competition.GetCompetitionQuestionListResp, error) {
	l := logic.NewGetCompetitionQuestionListLogic(ctx, s.svcCtx)
	return l.GetCompetitionQuestionList(in)
}

func (s *CompetitionServer) GetCompetitionQuestionDetail(ctx context.Context, in *competition.GetCompetitionQuestionDetailReq) (*competition.GetCompetitionQuestionDetailResp, error) {
	l := logic.NewGetCompetitionQuestionDetailLogic(ctx, s.svcCtx)
	return l.GetCompetitionQuestionDetail(in)
}

func (s *CompetitionServer) SubmitCompetitionQuestion(ctx context.Context, in *competition.SubmitCompetitionQuestionReq) (*competition.SubmitCompetitionQuestionResp, error) {
	l := logic.NewSubmitCompetitionQuestionLogic(ctx, s.svcCtx)
	return l.SubmitCompetitionQuestion(in)
}

func (s *CompetitionServer) ContestAccessCheck(ctx context.Context, in *competition.ContestAccessCheckReq) (*competition.ContestAccessCheckResp, error) {
	l := logic.NewContestAccessCheckLogic(ctx, s.svcCtx)
	return l.ContestAccessCheck(in)
}

func (s *CompetitionServer) GetCompetitionRankList(ctx context.Context, in *competition.GetCompetitionRankListReq) (*competition.GetCompetitionRankListResp, error) {
	l := logic.NewGetCompetitionRankListLogic(ctx, s.svcCtx)
	return l.GetCompetitionRankList(in)
}

func (s *CompetitionServer) IsUserInCompetition(ctx context.Context, in *competition.IsUserInCompetitionReq) (*competition.IsUserInCompetitionResp, error) {
	l := logic.NewIsUserInCompetitionLogic(ctx, s.svcCtx)
	return l.IsUserInCompetition(in)
}
