// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: question.proto

package questionclient

import (
	"context"

	"backend/rpc/question/pb/question"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PaginationRequest         = question.PaginationRequest
	PaginationResponse        = question.PaginationResponse
	QuestionBasicInfo         = question.QuestionBasicInfo
	QuestionInfoResponse      = question.QuestionInfoResponse
	QuestionJudgeCaseResponse = question.QuestionJudgeCaseResponse
	QuestionRequest           = question.QuestionRequest

	Question interface {
		GetQuestionInfo(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionInfoResponse, error)
		GetQuestionJudgeCase(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionJudgeCaseResponse, error)
		Pagination(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginationResponse, error)
	}

	defaultQuestion struct {
		cli zrpc.Client
	}
)

func NewQuestion(cli zrpc.Client) Question {
	return &defaultQuestion{
		cli: cli,
	}
}

func (m *defaultQuestion) GetQuestionInfo(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionInfoResponse, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.GetQuestionInfo(ctx, in, opts...)
}

func (m *defaultQuestion) GetQuestionJudgeCase(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionJudgeCaseResponse, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.GetQuestionJudgeCase(ctx, in, opts...)
}

func (m *defaultQuestion) Pagination(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginationResponse, error) {
	client := question.NewQuestionClient(m.cli.Conn())
	return client.Pagination(ctx, in, opts...)
}
