// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: judge.proto

package judgeclient

import (
	"context"

	"backend/microservices/judge/pb/judge"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecDetail       = judge.ExecDetail
	GetJudgeInfoReq  = judge.GetJudgeInfoReq
	GetJudgeInfoResp = judge.GetJudgeInfoResp
	GetJudgeListReq  = judge.GetJudgeListReq
	GetJudgeListResp = judge.GetJudgeListResp
	JudgeInfo        = judge.JudgeInfo
	JudgeReq         = judge.JudgeReq
	JudgeResp        = judge.JudgeResp

	Judge interface {
		Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error)
		GetJudgeList(ctx context.Context, in *GetJudgeListReq, opts ...grpc.CallOption) (*GetJudgeListResp, error)
		GetJudgeInfo(ctx context.Context, in *GetJudgeInfoReq, opts ...grpc.CallOption) (*GetJudgeInfoResp, error)
	}

	defaultJudge struct {
		cli zrpc.Client
	}
)

func NewJudge(cli zrpc.Client) Judge {
	return &defaultJudge{
		cli: cli,
	}
}

func (m *defaultJudge) Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error) {
	client := judge.NewJudgeClient(m.cli.Conn())
	return client.Judge(ctx, in, opts...)
}

func (m *defaultJudge) GetJudgeList(ctx context.Context, in *GetJudgeListReq, opts ...grpc.CallOption) (*GetJudgeListResp, error) {
	client := judge.NewJudgeClient(m.cli.Conn())
	return client.GetJudgeList(ctx, in, opts...)
}

func (m *defaultJudge) GetJudgeInfo(ctx context.Context, in *GetJudgeInfoReq, opts ...grpc.CallOption) (*GetJudgeInfoResp, error) {
	client := judge.NewJudgeClient(m.cli.Conn())
	return client.GetJudgeInfo(ctx, in, opts...)
}
