// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"
	"time"

	ai "backend/gateway/internal/handler/ai"
	competition "backend/gateway/internal/handler/competition"
	judge "backend/gateway/internal/handler/judge"
	question "backend/gateway/internal/handler/question"
	user "backend/gateway/internal/handler/user"
	"backend/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.BlockDuringCompetition},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/ai/chat",
					Handler: ai.ChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ai/code/check",
					Handler: ai.CodeCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ai/question/sessions",
					Handler: ai.GetQuestionSessionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ai/session/chat/history",
					Handler: ai.GetSessionMessageHistoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(600000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/competition/list",
				Handler: competition.GetCompetitionListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/attend",
					Handler: competition.AttendCompetitionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.CheckContestAccess, serverCtx.RequireContestPermission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/info",
					Handler: competition.GetCompetitionInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.CheckContestAccess, serverCtx.RequireContestPermission, serverCtx.RequireContestStarted},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/question/detail",
					Handler: competition.GetCompetitionQuestionDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/question/list",
					Handler: competition.GetCompetitionQuestionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/rank/list",
					Handler: competition.GetCompetitionRankListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.CheckContestAccess, serverCtx.RequireContestPermission, serverCtx.RequireContestRunning},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/question/submit",
					Handler: competition.SubmitCompetitionQuestionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/add",
					Handler: competition.AddCompetitionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/delete",
					Handler: competition.DeleteCompetitionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/list",
					Handler: competition.AdminGetCompetitionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/update",
					Handler: competition.UpdateCompetitionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/judge/judgecode",
					Handler: judge.JudgeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(600000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/judge/list",
					Handler: judge.GetJudgeListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/question/basic_info",
				Handler: question.GetQuestionBasicInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/question/public_list",
				Handler: question.GetPublicQuestionListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/question/add",
					Handler: question.AddQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/delete",
					Handler: question.DeleteQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/list",
					Handler: question.GetQuestionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/update",
					Handler: question.UpdateQuestionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/public_info",
				Handler: user.GetPublicInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/refresh_token",
				Handler: user.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update_password",
					Handler: user.UpdateUserPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update_personal_info",
					Handler: user.UpdatePersonalInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/add",
					Handler: user.AddUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/delete",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/list",
					Handler: user.GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: user.UpdateUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)
}
