// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	ai2 "backend/gateway/internal/handler/ai"
	competition2 "backend/gateway/internal/handler/competition"
	judge2 "backend/gateway/internal/handler/judge"
	question2 "backend/gateway/internal/handler/question"
	user2 "backend/gateway/internal/handler/user"
	"backend/gateway/internal/svc"
	"net/http"
	"time"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.BlockDuringCompetition},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/ai/chat",
					Handler: ai2.ChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ai/code/check",
					Handler: ai2.CodeCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ai/question/sessions",
					Handler: ai2.GetQuestionSessionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ai/session/chat/history",
					Handler: ai2.GetSessionMessageHistoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(600000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/competition/list",
				Handler: competition2.GetCompetitionListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/attend",
					Handler: competition2.AttendCompetitionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.CheckContestAccess, serverCtx.RequireContestPermission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/info",
					Handler: competition2.GetCompetitionInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.CheckContestAccess, serverCtx.RequireContestPermission, serverCtx.RequireContestStarted},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/question/detail",
					Handler: competition2.GetCompetitionQuestionDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/question/list",
					Handler: competition2.GetCompetitionQuestionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/rank/list",
					Handler: competition2.GetCompetitionRankListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.CheckContestAccess, serverCtx.RequireContestPermission, serverCtx.RequireContestRunning},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/question/submit",
					Handler: competition2.SubmitCompetitionQuestionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/competition/add",
					Handler: competition2.AddCompetitionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/delete",
					Handler: competition2.DeleteCompetitionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/list",
					Handler: competition2.AdminGetCompetitionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/competition/update",
					Handler: competition2.UpdateCompetitionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/judge/judgecode",
					Handler: judge2.JudgeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(600000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/judge/list",
					Handler: judge2.GetJudgeListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/question/basic_info",
				Handler: question2.GetQuestionBasicInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/question/public_list",
				Handler: question2.GetPublicQuestionListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/question/add",
					Handler: question2.AddQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/delete",
					Handler: question2.DeleteQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/list",
					Handler: question2.GetQuestionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/update",
					Handler: question2.UpdateQuestionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user2.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/public_info",
				Handler: user2.GetPublicInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/refresh_token",
				Handler: user2.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user2.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/info",
					Handler: user2.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/logout",
					Handler: user2.LogoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessTokenAuth, serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/add",
					Handler: user2.AddUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/delete",
					Handler: user2.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/list",
					Handler: user2.GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: user2.UpdateUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)
}
