// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: question.proto

package question

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Question_AddQuestion_FullMethodName            = "/question.Question/AddQuestion"
	Question_DeleteQuestion_FullMethodName         = "/question.Question/DeleteQuestion"
	Question_UpdateQuestion_FullMethodName         = "/question.Question/UpdateQuestion"
	Question_GetQuestionInfo_FullMethodName        = "/question.Question/GetQuestionInfo"
	Question_GetQuestionList_FullMethodName        = "/question.Question/GetQuestionList"
	Question_GetQuestionJudgeCase_FullMethodName   = "/question.Question/GetQuestionJudgeCase"
	Question_GetQuestionJudgeConfig_FullMethodName = "/question.Question/GetQuestionJudgeConfig"
	Question_AddSubmitNum_FullMethodName           = "/question.Question/AddSubmitNum"
	Question_AddAcceptedNum_FullMethodName         = "/question.Question/AddAcceptedNum"
)

// QuestionClient is the client API for Question service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 题目服务
type QuestionClient interface {
	AddQuestion(ctx context.Context, in *AddQuestionReq, opts ...grpc.CallOption) (*AddQuestionResp, error)
	DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionResp, error)
	UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionResp, error)
	GetQuestionInfo(ctx context.Context, in *GetQuestionInfoReq, opts ...grpc.CallOption) (*GetQuestionInfoResp, error)
	GetQuestionList(ctx context.Context, in *GetQuestionListReq, opts ...grpc.CallOption) (*GetQuestionListResp, error)
	GetQuestionJudgeCase(ctx context.Context, in *GetQuestionJudgeCaseReq, opts ...grpc.CallOption) (*GetQuestionJudgeCaseResp, error)
	GetQuestionJudgeConfig(ctx context.Context, in *GetQuestionJudgeConfigReq, opts ...grpc.CallOption) (*GetQuestionJudgeConfigResp, error)
	AddSubmitNum(ctx context.Context, in *AddSubmitNumReq, opts ...grpc.CallOption) (*AddSubmitNumResp, error)
	AddAcceptedNum(ctx context.Context, in *AddAcceptedNumReq, opts ...grpc.CallOption) (*AddAcceptedNumResp, error)
}

type questionClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionClient(cc grpc.ClientConnInterface) QuestionClient {
	return &questionClient{cc}
}

func (c *questionClient) AddQuestion(ctx context.Context, in *AddQuestionReq, opts ...grpc.CallOption) (*AddQuestionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddQuestionResp)
	err := c.cc.Invoke(ctx, Question_AddQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQuestionResp)
	err := c.cc.Invoke(ctx, Question_DeleteQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuestionResp)
	err := c.cc.Invoke(ctx, Question_UpdateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionInfo(ctx context.Context, in *GetQuestionInfoReq, opts ...grpc.CallOption) (*GetQuestionInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionInfoResp)
	err := c.cc.Invoke(ctx, Question_GetQuestionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionList(ctx context.Context, in *GetQuestionListReq, opts ...grpc.CallOption) (*GetQuestionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionListResp)
	err := c.cc.Invoke(ctx, Question_GetQuestionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionJudgeCase(ctx context.Context, in *GetQuestionJudgeCaseReq, opts ...grpc.CallOption) (*GetQuestionJudgeCaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionJudgeCaseResp)
	err := c.cc.Invoke(ctx, Question_GetQuestionJudgeCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionJudgeConfig(ctx context.Context, in *GetQuestionJudgeConfigReq, opts ...grpc.CallOption) (*GetQuestionJudgeConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionJudgeConfigResp)
	err := c.cc.Invoke(ctx, Question_GetQuestionJudgeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) AddSubmitNum(ctx context.Context, in *AddSubmitNumReq, opts ...grpc.CallOption) (*AddSubmitNumResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSubmitNumResp)
	err := c.cc.Invoke(ctx, Question_AddSubmitNum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) AddAcceptedNum(ctx context.Context, in *AddAcceptedNumReq, opts ...grpc.CallOption) (*AddAcceptedNumResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAcceptedNumResp)
	err := c.cc.Invoke(ctx, Question_AddAcceptedNum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServer is the server API for Question service.
// All implementations must embed UnimplementedQuestionServer
// for forward compatibility.
//
// 题目服务
type QuestionServer interface {
	AddQuestion(context.Context, *AddQuestionReq) (*AddQuestionResp, error)
	DeleteQuestion(context.Context, *DeleteQuestionReq) (*DeleteQuestionResp, error)
	UpdateQuestion(context.Context, *UpdateQuestionReq) (*UpdateQuestionResp, error)
	GetQuestionInfo(context.Context, *GetQuestionInfoReq) (*GetQuestionInfoResp, error)
	GetQuestionList(context.Context, *GetQuestionListReq) (*GetQuestionListResp, error)
	GetQuestionJudgeCase(context.Context, *GetQuestionJudgeCaseReq) (*GetQuestionJudgeCaseResp, error)
	GetQuestionJudgeConfig(context.Context, *GetQuestionJudgeConfigReq) (*GetQuestionJudgeConfigResp, error)
	AddSubmitNum(context.Context, *AddSubmitNumReq) (*AddSubmitNumResp, error)
	AddAcceptedNum(context.Context, *AddAcceptedNumReq) (*AddAcceptedNumResp, error)
	mustEmbedUnimplementedQuestionServer()
}

// UnimplementedQuestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuestionServer struct{}

func (UnimplementedQuestionServer) AddQuestion(context.Context, *AddQuestionReq) (*AddQuestionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddQuestion not implemented")
}
func (UnimplementedQuestionServer) DeleteQuestion(context.Context, *DeleteQuestionReq) (*DeleteQuestionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuestion not implemented")
}
func (UnimplementedQuestionServer) UpdateQuestion(context.Context, *UpdateQuestionReq) (*UpdateQuestionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuestion not implemented")
}
func (UnimplementedQuestionServer) GetQuestionInfo(context.Context, *GetQuestionInfoReq) (*GetQuestionInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionInfo not implemented")
}
func (UnimplementedQuestionServer) GetQuestionList(context.Context, *GetQuestionListReq) (*GetQuestionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionList not implemented")
}
func (UnimplementedQuestionServer) GetQuestionJudgeCase(context.Context, *GetQuestionJudgeCaseReq) (*GetQuestionJudgeCaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionJudgeCase not implemented")
}
func (UnimplementedQuestionServer) GetQuestionJudgeConfig(context.Context, *GetQuestionJudgeConfigReq) (*GetQuestionJudgeConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionJudgeConfig not implemented")
}
func (UnimplementedQuestionServer) AddSubmitNum(context.Context, *AddSubmitNumReq) (*AddSubmitNumResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSubmitNum not implemented")
}
func (UnimplementedQuestionServer) AddAcceptedNum(context.Context, *AddAcceptedNumReq) (*AddAcceptedNumResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAcceptedNum not implemented")
}
func (UnimplementedQuestionServer) mustEmbedUnimplementedQuestionServer() {}
func (UnimplementedQuestionServer) testEmbeddedByValue()                  {}

// UnsafeQuestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionServer will
// result in compilation errors.
type UnsafeQuestionServer interface {
	mustEmbedUnimplementedQuestionServer()
}

func RegisterQuestionServer(s grpc.ServiceRegistrar, srv QuestionServer) {
	// If the following call pancis, it indicates UnimplementedQuestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Question_ServiceDesc, srv)
}

func _Question_AddQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).AddQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_AddQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).AddQuestion(ctx, req.(*AddQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_DeleteQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_DeleteQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).DeleteQuestion(ctx, req.(*DeleteQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_UpdateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).UpdateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_UpdateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).UpdateQuestion(ctx, req.(*UpdateQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionInfo(ctx, req.(*GetQuestionInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionList(ctx, req.(*GetQuestionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionJudgeCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionJudgeCaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionJudgeCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionJudgeCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionJudgeCase(ctx, req.(*GetQuestionJudgeCaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionJudgeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionJudgeConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionJudgeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionJudgeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionJudgeConfig(ctx, req.(*GetQuestionJudgeConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_AddSubmitNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSubmitNumReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).AddSubmitNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_AddSubmitNum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).AddSubmitNum(ctx, req.(*AddSubmitNumReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_AddAcceptedNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAcceptedNumReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).AddAcceptedNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_AddAcceptedNum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).AddAcceptedNum(ctx, req.(*AddAcceptedNumReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Question_ServiceDesc is the grpc.ServiceDesc for Question service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Question_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "question.Question",
	HandlerType: (*QuestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddQuestion",
			Handler:    _Question_AddQuestion_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _Question_DeleteQuestion_Handler,
		},
		{
			MethodName: "UpdateQuestion",
			Handler:    _Question_UpdateQuestion_Handler,
		},
		{
			MethodName: "GetQuestionInfo",
			Handler:    _Question_GetQuestionInfo_Handler,
		},
		{
			MethodName: "GetQuestionList",
			Handler:    _Question_GetQuestionList_Handler,
		},
		{
			MethodName: "GetQuestionJudgeCase",
			Handler:    _Question_GetQuestionJudgeCase_Handler,
		},
		{
			MethodName: "GetQuestionJudgeConfig",
			Handler:    _Question_GetQuestionJudgeConfig_Handler,
		},
		{
			MethodName: "AddSubmitNum",
			Handler:    _Question_AddSubmitNum_Handler,
		},
		{
			MethodName: "AddAcceptedNum",
			Handler:    _Question_AddAcceptedNum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "question.proto",
}
