// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: judge.proto

package judge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Judge_Judge_FullMethodName        = "/judge.Judge/Judge"
	Judge_GetJudgeList_FullMethodName = "/judge.Judge/GetJudgeList"
	Judge_GetJudgeInfo_FullMethodName = "/judge.Judge/GetJudgeInfo"
)

// JudgeClient is the client API for Judge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JudgeClient interface {
	Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error)
	GetJudgeList(ctx context.Context, in *GetJudgeListReq, opts ...grpc.CallOption) (*GetJudgeListResp, error)
	GetJudgeInfo(ctx context.Context, in *GetJudgeInfoReq, opts ...grpc.CallOption) (*GetJudgeInfoResp, error)
}

type judgeClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeClient(cc grpc.ClientConnInterface) JudgeClient {
	return &judgeClient{cc}
}

func (c *judgeClient) Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JudgeResp)
	err := c.cc.Invoke(ctx, Judge_Judge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeClient) GetJudgeList(ctx context.Context, in *GetJudgeListReq, opts ...grpc.CallOption) (*GetJudgeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJudgeListResp)
	err := c.cc.Invoke(ctx, Judge_GetJudgeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeClient) GetJudgeInfo(ctx context.Context, in *GetJudgeInfoReq, opts ...grpc.CallOption) (*GetJudgeInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJudgeInfoResp)
	err := c.cc.Invoke(ctx, Judge_GetJudgeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeServer is the server API for Judge service.
// All implementations must embed UnimplementedJudgeServer
// for forward compatibility.
type JudgeServer interface {
	Judge(context.Context, *JudgeReq) (*JudgeResp, error)
	GetJudgeList(context.Context, *GetJudgeListReq) (*GetJudgeListResp, error)
	GetJudgeInfo(context.Context, *GetJudgeInfoReq) (*GetJudgeInfoResp, error)
	mustEmbedUnimplementedJudgeServer()
}

// UnimplementedJudgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJudgeServer struct{}

func (UnimplementedJudgeServer) Judge(context.Context, *JudgeReq) (*JudgeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Judge not implemented")
}
func (UnimplementedJudgeServer) GetJudgeList(context.Context, *GetJudgeListReq) (*GetJudgeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJudgeList not implemented")
}
func (UnimplementedJudgeServer) GetJudgeInfo(context.Context, *GetJudgeInfoReq) (*GetJudgeInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJudgeInfo not implemented")
}
func (UnimplementedJudgeServer) mustEmbedUnimplementedJudgeServer() {}
func (UnimplementedJudgeServer) testEmbeddedByValue()               {}

// UnsafeJudgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeServer will
// result in compilation errors.
type UnsafeJudgeServer interface {
	mustEmbedUnimplementedJudgeServer()
}

func RegisterJudgeServer(s grpc.ServiceRegistrar, srv JudgeServer) {
	// If the following call pancis, it indicates UnimplementedJudgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Judge_ServiceDesc, srv)
}

func _Judge_Judge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JudgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).Judge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Judge_Judge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).Judge(ctx, req.(*JudgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judge_GetJudgeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJudgeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).GetJudgeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Judge_GetJudgeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).GetJudgeList(ctx, req.(*GetJudgeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judge_GetJudgeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJudgeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).GetJudgeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Judge_GetJudgeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).GetJudgeInfo(ctx, req.(*GetJudgeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Judge_ServiceDesc is the grpc.ServiceDesc for Judge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Judge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "judge.Judge",
	HandlerType: (*JudgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Judge",
			Handler:    _Judge_Judge_Handler,
		},
		{
			MethodName: "GetJudgeList",
			Handler:    _Judge_GetJudgeList_Handler,
		},
		{
			MethodName: "GetJudgeInfo",
			Handler:    _Judge_GetJudgeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judge.proto",
}
